---
# ClamAV checks for virus definition files on startup
# Disable this check if we are testing, or managing updates in a different way
# For testing only!

- name: Create eicar.com and build signature database
  become: true
  ansible.builtin.shell: |
    # This is done as an echo rather than ansible.builtin.copy to avoid triggering local AV
    echo -n 'X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*' > /root/eicar.com
    sigtool --md5 /root/eicar.com > /var/lib/clamav/eicar.hdb
  args:
    creates: /var/lib/clamav/eicar.hdb

- name: Correct permissions /var/lib/clamav
  become: true
  ansible.builtin.file:
    path: /var/lib/clamav
    state: directory
    mode: "0755"

# /etc/init.d/clamav-daemon checks for presence of some startup locations
- name: Create clamav dummy inc directories
  ansible.builtin.file:
    path: /var/lib/clamav/{{ item }}.inc
    state: directory
    mode: "0755"
  loop:
    - daily
    - main

# The role will attempt to start clamav but it would've failed as the
# definition files were missing. Force a retry.
- name: Enable clamav
  become: true
  service:
    name: clamav-daemon
    enabled: true
    state: started
