---
# ClamAV checks for virus definition files on startup
# Disable this check if we are testing, or managing updates in a different way
# For testing only!

- name: Create an EICAR signature db for ClamAV
  become: true
  copy:
    # This is the sha256 with file length and a name
    content: |
      44d88612fea8a8f36de82e1278abb02f:68:eicar
    dest: /var/lib/clamav/eicar.hdb

- name: Correct permissions /var/lib/clamav
  become: true
  ansible.builtin.file:
    path: /var/lib/clamav
    state: directory
    mode: "0755"

# /etc/init.d/clamav-daemon checks for presence of some startup locations
- name: Create clamav dummy inc directories
  ansible.builtin.file:
    path: /var/lib/clamav/{{ item }}.inc
    state: directory
    mode: "0755"
  loop:
    - daily
    - main

# The role will attempt to start clamav but it would've failed as the
# definition files were missing. Force a retry.
- name: Enable clamav
  become: true
  service:
    name: clamav-daemon
    enabled: true
    state: started
