---
- name: restart nginx
  become: true
  service:
    name: openresty
    state: restarted
    enabled: true

- name: restart fcgiwrap
  become: true
  service:
    name: fcgiwrap
    state: restarted
    enabled: true
