---
- name: restart httpd
  become: true
  service:
    name: apache2
    state: restarted
    enabled: true

- name: reload systemd-daemon
  become: true
  systemctl:
    daemon_reload: true

- name: restart docker
  become: true
  service:
    name: docker
    state: restarted
    enabled: true

- name: restart mongodb
  become: true
  service:
    name: mongodb
    state: restarted
    enabled: true
