---
- name: Converge
  hosts: all
  tasks:
    - name: Include hic.clamav
      ansible.builtin.include_role:
        name: hic.clamav
      vars:
        clamav_updates: false

    - name: Setup eicar test environment
      include_role:
        name: hic.clamav
        tasks_from: test-eicar
