---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: clamav
    image: ubuntu:20.04
    privileged: true
    pre_build_image: false
provisioner:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
verifier:
  name: ansible
