---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:24.04
    privileged: true
    pre_build_image: false
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        allowed_domains:
          - eu.httpbin.org
verifier:
  name: ansible
