---

- name: add testing endpoint to /etc/hosts
  become: true
  lineinfile:
    path: /etc/hosts
    line: 127.0.0.1 cran.{{zone}}
    unsafe_writes: true # issue with testing inside a container

- name: install R for testing package installation
  become: true
  apt:
    name:
      - r-base
      - build-essential
    install_recommends: false

- name: create faux sophos-spl installation
  become: true
  file:
    state: directory
    recurse: true
    dest: /opt/sophos-spl/plugins/av/bin

- name: create a faux avscanner tool
  become: true
  file:
    state: link
    src: /usr/bin/true
    dest: /opt/sophos-spl/plugins/av/bin/avscanner
