---
- name: Converge
  hosts: all
  tasks:
    - name: "Include hic.reverse_proxy"
      include_role:
        name: "hic.reverse_proxy"

    - name: add testing endpoint to /etc/hosts
      become: true
      lineinfile:
        path: /etc/hosts
        line: 127.0.0.1 cran.{{zone}}
        unsafe_writes: true # issue with testing inside a container

    - name: add testing endpoint to /etc/hosts
      become: true
      lineinfile:
        path: /etc/hosts
        line: 127.0.0.1 conda.{{zone}}
        unsafe_writes: true # issue with testing inside a container

    - name: install R for testing package installation
      become: true
      apt:
        name:
          - r-base
          - build-essential
        install_recommends: false

    - name: install ClamAV for a more proper test
      become: true
      apt:
        name:
          - clamav
        install_recommends: false
      register: clamav_install

    - name: Create an EICAR signature db for ClamAV
      copy:
        # This is the sha256 with file length and a name
        content: |
          131f95c51cc819465fa1797f6ccacf9d494aaaff46fa3eac73ae63ffbdfd8267:69:eicar
        dest: /tmp/clamav.hdb
      when: clamav_install.changed

    - name: create faux sophos-spl installation
      become: true
      file:
        state: directory
        recurse: true
        dest: /opt/sophos-spl/plugins/av/bin

    - name: create a faux avscanner tool
      become: true
      copy:
        content: |
          #!/bin/bash
          /usr/bin/clamscan -d /tmp/clamav.hdb $1
        dest: /opt/sophos-spl/plugins/av/bin/avscanner
        mode: u+rwx,g+rx,o+rx

    - name: download conda for testing
      get_url:
        # ansible_arch is likely either x86_64 or aarch64 which is the same naming format as miniconda uses.
        url: https://repo.anaconda.com/miniconda/Miniconda3-py310_22.11.1-1-Linux-{{ ansible_architecture }}.sh
        dest: /Miniconda3.sh
      register: conda_download

    - name: install conda
      shell: bash /Miniconda3.sh -b
      when: conda_download.changed

    - name: setup conda to use local proxy
      copy:
        dest: /root/.condarc
        content: |
          channels:
            - http://conda.{{ zone}}/conda-forge
          ssl_verify: False
