---
- name: Converge
  hosts: all
  tasks:
    - name: Include hic.clamav
      include_role:
        name: clamav
      vars:
        clamav_updates: false

    - name: Setup eicar test environment
      include_role:
        name: clamav
        tasks_from: test-eicar

    - name: "Include hic.reverse_proxy"
      include_role:
        name: reverse_proxy

    - name: add testing endpoint to /etc/hosts
      become: true
      lineinfile:
        path: /etc/hosts
        line: 127.0.0.1 cran.{{zone}}
        unsafe_writes: true # issue with testing inside a container

    - name: add testing endpoint to /etc/hosts
      become: true
      lineinfile:
        path: /etc/hosts
        line: 127.0.0.1 conda.{{zone}}
        unsafe_writes: true # issue with testing inside a container

    - name: add testing endpoint to /etc/hosts
      become: true
      lineinfile:
        path: /etc/hosts
        line: 127.0.0.1 bioconductor.{{zone}}
        unsafe_writes: true # issue with testing inside a container

    - name: break access to bioconductor.org for testing
      become: true
      lineinfile:
        path: /etc/hosts
        line: 255.255.255.255 bioconductor.org
        unsafe_writes: true # issue with testing inside a container

    - name: install R for testing package installation
      become: true
      apt:
        name:
          - r-base
          - build-essential
        install_recommends: false

    - name: create faux sophos-spl installation
      become: true
      file:
        state: directory
        recurse: true
        dest: /opt/sophos-spl/plugins/av/bin

    - name: create a faux avscanner tool
      become: true
      copy:
        content: |
          #!/bin/bash
          /usr/bin/clamscan -d /tmp/clamav.hdb $1
        dest: /opt/sophos-spl/plugins/av/bin/avscanner
        mode: u+rwx,g+rx,o+rx

    - name: download conda for testing
      get_url:
        # ansible_arch is likely either x86_64 or aarch64 which is the same naming format as miniconda uses.
        url: https://repo.anaconda.com/miniconda/Miniconda3-py310_22.11.1-1-Linux-{{ ansible_architecture }}.sh
        dest: /Miniconda3.sh
      register: conda_download

    - name: install conda
      shell: bash /Miniconda3.sh -b
      when: conda_download.changed

    - name: setup conda to use local proxy
      copy:
        dest: /root/.condarc
        content: |
          channels:
            - http://conda.{{ zone}}/conda-forge
          ssl_verify: False

    - name: create a bioconductor config for testing
      copy:
        dest: /root/config.yaml
        content: |
          ---
          output_dir: output
          staging_deploy_root: biocadmin@staging.bioconductor.org:/loc/www/bioconductor-test-new
          production_deploy_root: webadmin@master.bioconductor.org:/extra/www/bioc
          staging_dir: /loc/www/bioconductor-test-new

          release_version: "3.19"
          r_version_associated_with_release: "4.4.0"
          r_version_associated_with_devel: "4.4.0"

          devel_version: "3.20"

          versions:
          - "3.19"
          - "3.20"

          devel_repos:
          - "bioc"

          r_ver_for_bioc_ver:
            "1.6": "2.1"
            "1.7": "2.2"
            "1.8": "2.3"
            "1.9": "2.4"
            "2.0": "2.5"
            "2.1": "2.6"
            "2.2": "2.7"
            "2.3": "2.8"
            "2.4": "2.9"
            "2.5": "2.10"
            "2.6": "2.11"
            "2.7": "2.12"
            "2.8": "2.13"
            "2.9": "2.14"
            "2.10": "2.15"
            "2.11": "2.15" # R switching to yearly releases, BioC remaining the same
            "2.12": "3.0"
            "2.13": "3.0"
            "2.14": "3.1"
            "3.0": "3.1"
            "3.1": "3.2"
            "3.2": "3.2"
            "3.3": "3.3"
            "3.4": "3.3"
            "3.5": "3.4"
            "3.6": "3.4"
            "3.7": "3.5"
            "3.8": "3.5"
            "3.9": "3.6"
            "3.10": "3.6"
            "3.11": "4.0"
            "3.12": "4.0"
            "3.13": "4.1"
            "3.14": "4.1"
            "3.15": "4.2"
            "3.16": "4.2"
            "3.17": "4.3"
            "3.18": "4.3"
            "3.19": "4.4"
            "3.20": "4.4"
          # UPDATE THIS when we release a version
          release_dates: # old info from http://en.wikipedia.org/wiki/Bioconductor#Milestones
            "1.0": "1/5/2001"
            "1.1": "11/19/2002"
            "1.2": "5/29/2003"
            "1.3": "10/30/2003"
            "1.4": "5/17/2004"
            "1.5": "10/25/2004"
            "1.6": "5/18/2005"
            "1.7": "10/14/2005"
            "1.8": "4/27/2006"
            "1.9": "10/4/2006"
            "2.0": "4/26/2007"
            "2.1": "10/8/2007"
            "2.2": "5/1/2008"
            "2.3": "10/22/2008"
            "2.4": "4/21/2009"
            "2.5": "10/28/2009"
            "2.6": "4/23/2010"
            "2.7": "10/18/2010"
            "2.8": "4/14/2011"
            "2.9": "11/1/2011"
            "2.10": "4/2/2012"
            "2.11": "10/3/2012"
            "2.12": "4/4/2013"
            "2.13": "10/15/2013"
            "2.14": "4/14/2014"
            "3.0": "10/14/2014"
            "3.1": "4/17/2015"
            "3.2": "10/14/2015"
            "3.3": "5/4/2016"
            "3.4": "10/18/2016"
            "3.5": "4/25/2017"
            "3.6": "10/31/2017"
            "3.7": "05/01/2018"
            "3.8": "10/31/2018"
            "3.9": "05/03/2019"
            "3.10": "10/30/2019"
            "3.11": "04/28/2020"
            "3.12": "10/28/2020"
            "3.13": "05/20/2021"
            "3.14": "10/27/2021"
            "3.15": "04/27/2022"
            "3.16": "11/02/2022"
            "3.17": "04/26/2023"
            "3.18": "10/25/2023"
            "3.19": "05/01/2024"
          release_last_built_dates:
            '2.0': 09/12/2007
            '2.1': 04/09/2008
            '2.2': 10/16/2008
            '2.3': 04/18/2009
            '2.4': 10/20/2009
            '2.5': 04/03/2010
            '2.6': 10/05/2010
            '2.7': 04/07/2011
            '2.8': 10/21/2011
            '2.9': 03/24/2012
            '2.10': 09/24/2012
            '2.11': 03/25/2013
            '2.12': 10/09/2013
            '2.13': 04/05/2014
            '2.14': 10/08/2014
            '3.0': 04/10/2015
            '3.1': 10/09/2015
            '3.2': 04/23/2016
            '3.3': 10/13/2016
            '3.4': 04/15/2017
            '3.5': 10/18/2017
            '3.6': 04/12/2018
            '3.7': 10/17/2018
            '3.8': 04/16/2019
            '3.9': 10/16/2019
            '3.10': 04/15/2020
            '3.11': 10/17/2020
            '3.12': 05/06/2021
            '3.13': 10/15/2021
            '3.14': 04/13/2022
            '3.15': 10/19/2022
            '3.16': 04/12/2023
            '3.17': 10/16/2023
            '3.18': 04/17/2024
          mirrors:
           - 0-Bioconductor:
             - institution: Bioconductor, automatic redirection to servers worldwide
               institution_url: https://bioconductor.org
               contact: Bioconductor Maintainer
               contact_email: maintainer@bioconductor.org
               city: World-wide
               mirror_url: http://bioconductor.localhost/
               #https_mirror_url: https://bioconductor.org/
               rsync: secure_mirror_from_master
               country_code: us
