---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: reverse_proxy
    image: ubuntu:20.04
    privileged: true
    pre_build_image: false
provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      all:
        test: true
        zone: localhost
  env:
    # So that we can use hic.clamav
    ANSIBLE_ROLES_PATH: ../../../
verifier:
  name: ansible
